name: test_and_code
on: push
jobs:
  rubocop:
    name: Rubocop
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v1

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
        ruby-version: 3.1.2

    - name: Analyze code
      run: bundle exec rubocop

  rspec:
    name: Rspec
    runs-on: ubuntu-20.04
    env:
      RAILS_ENV: test
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/db_test
    services:
      postgres:
        image: postgres:latest
        ports: ['5432:5432']
        env:
          POSTGRES_DB: db/development.sqlite3
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
    - name: Checkout code
      uses: actions/checkout@v1

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
        ruby-version: 3.1.2

    - name: Install postgres client dependencies
      run: sudo apt-get install libpq-dev
    - name: Create database
      run: |
        bundle exec rails db:create
        bundle exec rails db:schema:load
        bundle exec rails db:structure:load
        bundle exec rails db:migrate

    - name: Run tests
      run: bundle exec rspec spec
